-- ============================================================
-- AgroSatMonitor API — Script Oracle SQL Completo
-- Projeto Acadêmico FIAP — Pós-Graduação em IA para Devs
-- ============================================================
-- Execute este script manualmente no SQL Developer ou
-- ferramenta Oracle equivalente antes de executar a API.
-- ============================================================

-- ============================================================
-- 1. DROP TABLES (ordem reversa de dependência)
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TB_HISTORICO_CONSULTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TB_ALERTA_AGRICOLA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TB_MON_VEGETACAO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TB_MON_CLIMATICO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TB_CULTURA_AGRICOLA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TB_FAZENDA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================
-- 2. DROP SEQUENCES
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_FAZENDA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CULTURA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_MON_CLI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_MON_VEG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_ALERTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_HISTORICO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- 3. CREATE SEQUENCES
-- ============================================================
CREATE SEQUENCE SQ_FAZENDA   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_CULTURA   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_MON_CLI   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_MON_VEG   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_ALERTA    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_HISTORICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- 4. CREATE TABLES
-- ============================================================

-- TB_FAZENDA
CREATE TABLE TB_FAZENDA (
    ID_FAZENDA       NUMBER(10)     DEFAULT SQ_FAZENDA.NEXTVAL NOT NULL,
    NM_FAZENDA       VARCHAR2(200)  NOT NULL,
    NR_LATITUDE      NUMBER(10,6)   NOT NULL,
    NR_LONGITUDE     NUMBER(10,6)   NOT NULL,
    NR_AREA_HECTARES NUMBER(12,2),
    NM_CIDADE        VARCHAR2(100)  NOT NULL,
    SG_ESTADO        CHAR(2)        NOT NULL,
    DT_CADASTRO      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FAZENDA PRIMARY KEY (ID_FAZENDA)
);

COMMENT ON TABLE  TB_FAZENDA             IS 'Cadastro de fazendas monitoradas';
COMMENT ON COLUMN TB_FAZENDA.ID_FAZENDA  IS 'Identificador único da fazenda';
COMMENT ON COLUMN TB_FAZENDA.NM_FAZENDA  IS 'Nome da fazenda';
COMMENT ON COLUMN TB_FAZENDA.NR_LATITUDE IS 'Latitude geográfica da fazenda';
COMMENT ON COLUMN TB_FAZENDA.NR_LONGITUDE IS 'Longitude geográfica da fazenda';

-- TB_CULTURA_AGRICOLA
CREATE TABLE TB_CULTURA_AGRICOLA (
    ID_CULTURA  NUMBER(10)    DEFAULT SQ_CULTURA.NEXTVAL NOT NULL,
    NM_CULTURA  VARCHAR2(100) NOT NULL,
    TP_CULTURA  VARCHAR2(100) NOT NULL,
    DS_SAFRA    VARCHAR2(20)  NOT NULL,
    ID_FAZENDA  NUMBER(10)    NOT NULL,
    CONSTRAINT PK_CULTURA    PRIMARY KEY (ID_CULTURA),
    CONSTRAINT FK_CULT_FAZ   FOREIGN KEY (ID_FAZENDA) REFERENCES TB_FAZENDA (ID_FAZENDA) ON DELETE CASCADE
);

COMMENT ON TABLE TB_CULTURA_AGRICOLA IS 'Culturas agrícolas plantadas em cada fazenda';

-- TB_MON_CLIMATICO (herda de MonitoramentoBase via TPC)
CREATE TABLE TB_MON_CLIMATICO (
    ID_MON_CLI     NUMBER(10)   DEFAULT SQ_MON_CLI.NEXTVAL NOT NULL,
    ID_FAZENDA     NUMBER(10)   NOT NULL,
    NR_LATITUDE    NUMBER(10,6) NOT NULL,
    NR_LONGITUDE   NUMBER(10,6) NOT NULL,
    DT_CRIACAO     TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    NR_TEMPERATURA NUMBER(6,2)  NOT NULL,
    NR_UMIDADE     NUMBER(6,2)  NOT NULL,
    NR_PRECIPITACAO NUMBER(8,2) NOT NULL,
    NR_VEL_VENTO   NUMBER(8,2)  NOT NULL,
    DT_LEITURA     TIMESTAMP    NOT NULL,
    CONSTRAINT PK_MON_CLI     PRIMARY KEY (ID_MON_CLI),
    CONSTRAINT FK_CLI_FAZ     FOREIGN KEY (ID_FAZENDA) REFERENCES TB_FAZENDA (ID_FAZENDA) ON DELETE CASCADE
);

COMMENT ON TABLE  TB_MON_CLIMATICO              IS 'Histórico de monitoramentos climáticos por fazenda';
COMMENT ON COLUMN TB_MON_CLIMATICO.NR_TEMPERATURA IS 'Temperatura em graus Celsius';
COMMENT ON COLUMN TB_MON_CLIMATICO.NR_UMIDADE     IS 'Umidade relativa do ar em percentual';
COMMENT ON COLUMN TB_MON_CLIMATICO.NR_PRECIPITACAO IS 'Precipitação em milímetros';
COMMENT ON COLUMN TB_MON_CLIMATICO.NR_VEL_VENTO   IS 'Velocidade do vento em km/h';

-- TB_MON_VEGETACAO (herda de MonitoramentoBase via TPC)
CREATE TABLE TB_MON_VEGETACAO (
    ID_MON_VEG     NUMBER(10)   DEFAULT SQ_MON_VEG.NEXTVAL NOT NULL,
    ID_FAZENDA     NUMBER(10)   NOT NULL,
    NR_LATITUDE    NUMBER(10,6) NOT NULL,
    NR_LONGITUDE   NUMBER(10,6) NOT NULL,
    DT_CRIACAO     TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    NR_NDVI        NUMBER(7,4)  NOT NULL,
    TP_NIVEL_SAUDE NUMBER(1)    NOT NULL,
    DT_LEITURA     TIMESTAMP    NOT NULL,
    CONSTRAINT PK_MON_VEG     PRIMARY KEY (ID_MON_VEG),
    CONSTRAINT FK_VEG_FAZ     FOREIGN KEY (ID_FAZENDA) REFERENCES TB_FAZENDA (ID_FAZENDA) ON DELETE CASCADE,
    CONSTRAINT CK_NIVEL_SAUDE CHECK (TP_NIVEL_SAUDE BETWEEN 1 AND 5)
);

COMMENT ON TABLE  TB_MON_VEGETACAO          IS 'Histórico de monitoramentos de vegetação (NDVI) por fazenda';
COMMENT ON COLUMN TB_MON_VEGETACAO.NR_NDVI  IS 'Índice de vegetação NDVI (-1 a 1)';
COMMENT ON COLUMN TB_MON_VEGETACAO.TP_NIVEL_SAUDE IS '1=Critica 2=Baixa 3=Moderada 4=Boa 5=Excelente';

-- TB_ALERTA_AGRICOLA
CREATE TABLE TB_ALERTA_AGRICOLA (
    ID_ALERTA      NUMBER(10)   DEFAULT SQ_ALERTA.NEXTVAL NOT NULL,
    ID_FAZENDA     NUMBER(10)   NOT NULL,
    TP_ALERTA      NUMBER(1)    NOT NULL,
    DS_ALERTA      VARCHAR2(500),
    TP_NIVEL_RISCO NUMBER(1)    NOT NULL,
    DT_GERACAO     TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERTA       PRIMARY KEY (ID_ALERTA),
    CONSTRAINT FK_ALERT_FAZ    FOREIGN KEY (ID_FAZENDA) REFERENCES TB_FAZENDA (ID_FAZENDA) ON DELETE CASCADE,
    CONSTRAINT CK_TP_ALERTA    CHECK (TP_ALERTA    BETWEEN 1 AND 5),
    CONSTRAINT CK_TP_NIVEL     CHECK (TP_NIVEL_RISCO BETWEEN 1 AND 4)
);

COMMENT ON TABLE  TB_ALERTA_AGRICOLA           IS 'Alertas agrícolas gerados automaticamente pela API';
COMMENT ON COLUMN TB_ALERTA_AGRICOLA.TP_ALERTA IS '1=Seca 2=TemperaturaExtrema 3=BaixaVegetacao 4=ChuvaExcessiva 5=VentoForte';
COMMENT ON COLUMN TB_ALERTA_AGRICOLA.TP_NIVEL_RISCO IS '1=Baixo 2=Medio 3=Alto 4=Critico';

-- TB_HISTORICO_CONSULTA
CREATE TABLE TB_HISTORICO_CONSULTA (
    ID_HISTORICO    NUMBER(10)   DEFAULT SQ_HISTORICO.NEXTVAL NOT NULL,
    ID_FAZENDA      NUMBER(10)   NOT NULL,
    DS_ENDPOINT     VARCHAR2(300),
    DT_CONSULTA     TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    NR_TEMPO_RESP_MS NUMBER(10)  NOT NULL,
    FL_SUCESSO      NUMBER(1)    DEFAULT 1 NOT NULL,
    CONSTRAINT PK_HISTORICO     PRIMARY KEY (ID_HISTORICO),
    CONSTRAINT FK_HIST_FAZ      FOREIGN KEY (ID_FAZENDA) REFERENCES TB_FAZENDA (ID_FAZENDA) ON DELETE CASCADE,
    CONSTRAINT CK_FL_SUCESSO    CHECK (FL_SUCESSO IN (0,1))
);

COMMENT ON TABLE  TB_HISTORICO_CONSULTA IS 'Log de todas as consultas realizadas às APIs externas';
COMMENT ON COLUMN TB_HISTORICO_CONSULTA.FL_SUCESSO IS '1=Sucesso 0=Falha';

-- ============================================================
-- 5. INDEXES
-- ============================================================
CREATE INDEX IDX_CULT_FAZENDA ON TB_CULTURA_AGRICOLA (ID_FAZENDA);
CREATE INDEX IDX_CLI_FAZENDA  ON TB_MON_CLIMATICO    (ID_FAZENDA, DT_LEITURA DESC);
CREATE INDEX IDX_VEG_FAZENDA  ON TB_MON_VEGETACAO    (ID_FAZENDA, DT_LEITURA DESC);
CREATE INDEX IDX_ALERT_FAZ    ON TB_ALERTA_AGRICOLA  (ID_FAZENDA, DT_GERACAO DESC);
CREATE INDEX IDX_HIST_FAZ     ON TB_HISTORICO_CONSULTA (ID_FAZENDA, DT_CONSULTA DESC);

-- ============================================================
-- 6. INSERTS — FAZENDAS
-- ============================================================
INSERT INTO TB_FAZENDA (NM_FAZENDA, NR_LATITUDE, NR_LONGITUDE, NR_AREA_HECTARES, NM_CIDADE, SG_ESTADO, DT_CADASTRO)
VALUES ('Fazenda Santa Cruz', -22.9099, -47.0626, 1850.50, 'Campinas', 'SP', SYSTIMESTAMP);

INSERT INTO TB_FAZENDA (NM_FAZENDA, NR_LATITUDE, NR_LONGITUDE, NR_AREA_HECTARES, NM_CIDADE, SG_ESTADO, DT_CADASTRO)
VALUES ('Agropecuária Bela Vista', -15.7801, -47.9292, 3200.00, 'Brasília', 'DF', SYSTIMESTAMP);

INSERT INTO TB_FAZENDA (NM_FAZENDA, NR_LATITUDE, NR_LONGITUDE, NR_AREA_HECTARES, NM_CIDADE, SG_ESTADO, DT_CADASTRO)
VALUES ('Fazenda São João do Cerrado', -17.3253, -46.5000, 2750.75, 'Paracatu', 'MG', SYSTIMESTAMP);

INSERT INTO TB_FAZENDA (NM_FAZENDA, NR_LATITUDE, NR_LONGITUDE, NR_AREA_HECTARES, NM_CIDADE, SG_ESTADO, DT_CADASTRO)
VALUES ('Rancho Verde Vivo', -12.9714, -38.5014, 980.00, 'Salvador', 'BA', SYSTIMESTAMP);

INSERT INTO TB_FAZENDA (NM_FAZENDA, NR_LATITUDE, NR_LONGITUDE, NR_AREA_HECTARES, NM_CIDADE, SG_ESTADO, DT_CADASTRO)
VALUES ('Fazenda Primavera Gaucha', -30.0346, -51.2177, 4100.20, 'Porto Alegre', 'RS', SYSTIMESTAMP);

-- ============================================================
-- 7. INSERTS — CULTURAS AGRÍCOLAS
-- ============================================================
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Soja', 'Grão', '2024/2025', 1);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Milho', 'Grão', '2024/2025', 1);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Cana-de-Açúcar', 'Matéria Prima', '2024', 1);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Soja', 'Grão', '2024/2025', 2);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Algodão', 'Fibra', '2024/2025', 2);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Café Arábica', 'Grão', '2024', 3);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Milho', 'Grão', '2024/2025', 3);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Cacau', 'Fruto', '2024', 4);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Mandioca', 'Raiz', '2024', 4);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Arroz', 'Grão', '2024/2025', 5);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Soja', 'Grão', '2024/2025', 5);
INSERT INTO TB_CULTURA_AGRICOLA (NM_CULTURA, TP_CULTURA, DS_SAFRA, ID_FAZENDA) VALUES ('Trigo', 'Grão', '2024', 5);

-- ============================================================
-- 8. INSERTS — MONITORAMENTOS CLIMÁTICOS
-- ============================================================
INSERT INTO TB_MON_CLIMATICO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_TEMPERATURA, NR_UMIDADE, NR_PRECIPITACAO, NR_VEL_VENTO, DT_LEITURA)
VALUES (1, -22.9099, -47.0626, SYSTIMESTAMP - INTERVAL '5' DAY, 28.5, 72.0, 2.4, 15.2, SYSTIMESTAMP - INTERVAL '5' DAY);

INSERT INTO TB_MON_CLIMATICO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_TEMPERATURA, NR_UMIDADE, NR_PRECIPITACAO, NR_VEL_VENTO, DT_LEITURA)
VALUES (1, -22.9099, -47.0626, SYSTIMESTAMP - INTERVAL '4' DAY, 31.2, 58.0, 0.0, 22.1, SYSTIMESTAMP - INTERVAL '4' DAY);

INSERT INTO TB_MON_CLIMATICO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_TEMPERATURA, NR_UMIDADE, NR_PRECIPITACAO, NR_VEL_VENTO, DT_LEITURA)
VALUES (1, -22.9099, -47.0626, SYSTIMESTAMP - INTERVAL '3' DAY, 39.8, 25.0, 0.0, 18.5, SYSTIMESTAMP - INTERVAL '3' DAY);

INSERT INTO TB_MON_CLIMATICO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_TEMPERATURA, NR_UMIDADE, NR_PRECIPITACAO, NR_VEL_VENTO, DT_LEITURA)
VALUES (2, -15.7801, -47.9292, SYSTIMESTAMP - INTERVAL '2' DAY, 34.1, 42.0, 0.0, 28.3, SYSTIMESTAMP - INTERVAL '2' DAY);

INSERT INTO TB_MON_CLIMATICO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_TEMPERATURA, NR_UMIDADE, NR_PRECIPITACAO, NR_VEL_VENTO, DT_LEITURA)
VALUES (2, -15.7801, -47.9292, SYSTIMESTAMP - INTERVAL '1' DAY, 36.5, 30.0, 0.0, 31.0, SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO TB_MON_CLIMATICO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_TEMPERATURA, NR_UMIDADE, NR_PRECIPITACAO, NR_VEL_VENTO, DT_LEITURA)
VALUES (3, -17.3253, -46.5000, SYSTIMESTAMP - INTERVAL '3' DAY, 24.6, 80.0, 18.5, 12.4, SYSTIMESTAMP - INTERVAL '3' DAY);

INSERT INTO TB_MON_CLIMATICO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_TEMPERATURA, NR_UMIDADE, NR_PRECIPITACAO, NR_VEL_VENTO, DT_LEITURA)
VALUES (4, -12.9714, -38.5014, SYSTIMESTAMP - INTERVAL '2' DAY, 30.0, 85.0, 55.3, 10.0, SYSTIMESTAMP - INTERVAL '2' DAY);

INSERT INTO TB_MON_CLIMATICO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_TEMPERATURA, NR_UMIDADE, NR_PRECIPITACAO, NR_VEL_VENTO, DT_LEITURA)
VALUES (5, -30.0346, -51.2177, SYSTIMESTAMP - INTERVAL '1' DAY, 18.2, 68.0, 8.1, 45.5, SYSTIMESTAMP - INTERVAL '1' DAY);

-- ============================================================
-- 9. INSERTS — MONITORAMENTOS DE VEGETAÇÃO
-- ============================================================
INSERT INTO TB_MON_VEGETACAO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_NDVI, TP_NIVEL_SAUDE, DT_LEITURA)
VALUES (1, -22.9099, -47.0626, SYSTIMESTAMP - INTERVAL '5' DAY, 0.6812, 4, SYSTIMESTAMP - INTERVAL '5' DAY);

INSERT INTO TB_MON_VEGETACAO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_NDVI, TP_NIVEL_SAUDE, DT_LEITURA)
VALUES (1, -22.9099, -47.0626, SYSTIMESTAMP - INTERVAL '3' DAY, 0.4523, 3, SYSTIMESTAMP - INTERVAL '3' DAY);

INSERT INTO TB_MON_VEGETACAO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_NDVI, TP_NIVEL_SAUDE, DT_LEITURA)
VALUES (2, -15.7801, -47.9292, SYSTIMESTAMP - INTERVAL '2' DAY, 0.2190, 2, SYSTIMESTAMP - INTERVAL '2' DAY);

INSERT INTO TB_MON_VEGETACAO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_NDVI, TP_NIVEL_SAUDE, DT_LEITURA)
VALUES (2, -15.7801, -47.9292, SYSTIMESTAMP - INTERVAL '1' DAY, 0.0750, 1, SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO TB_MON_VEGETACAO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_NDVI, TP_NIVEL_SAUDE, DT_LEITURA)
VALUES (3, -17.3253, -46.5000, SYSTIMESTAMP - INTERVAL '3' DAY, 0.7340, 5, SYSTIMESTAMP - INTERVAL '3' DAY);

INSERT INTO TB_MON_VEGETACAO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_NDVI, TP_NIVEL_SAUDE, DT_LEITURA)
VALUES (4, -12.9714, -38.5014, SYSTIMESTAMP - INTERVAL '2' DAY, 0.5560, 4, SYSTIMESTAMP - INTERVAL '2' DAY);

INSERT INTO TB_MON_VEGETACAO (ID_FAZENDA, NR_LATITUDE, NR_LONGITUDE, DT_CRIACAO, NR_NDVI, TP_NIVEL_SAUDE, DT_LEITURA)
VALUES (5, -30.0346, -51.2177, SYSTIMESTAMP - INTERVAL '1' DAY, 0.3890, 3, SYSTIMESTAMP - INTERVAL '1' DAY);

-- ============================================================
-- 10. INSERTS — ALERTAS AGRÍCOLAS
-- ============================================================
-- Tipo: 1=Seca 2=TemperaturaExtrema 3=BaixaVegetacao 4=ChuvaExcessiva 5=VentoForte
-- Risco: 1=Baixo 2=Medio 3=Alto 4=Critico

INSERT INTO TB_ALERTA_AGRICOLA (ID_FAZENDA, TP_ALERTA, DS_ALERTA, TP_NIVEL_RISCO, DT_GERACAO)
VALUES (1, 2, 'Temperatura muito alta: 39.8°C. Risco de estresse térmico nas culturas. Recomenda-se irrigação emergencial e proteção das plantas.', 3, SYSTIMESTAMP - INTERVAL '3' DAY);

INSERT INTO TB_ALERTA_AGRICOLA (ID_FAZENDA, TP_ALERTA, DS_ALERTA, TP_NIVEL_RISCO, DT_GERACAO)
VALUES (1, 1, 'Condições de seca detectadas: precipitação 0.0mm, umidade 25.0%. Recomenda-se acionamento do sistema de irrigação.', 3, SYSTIMESTAMP - INTERVAL '3' DAY);

INSERT INTO TB_ALERTA_AGRICOLA (ID_FAZENDA, TP_ALERTA, DS_ALERTA, TP_NIVEL_RISCO, DT_GERACAO)
VALUES (2, 2, 'Temperatura muito alta: 36.5°C. Risco de estresse térmico nas culturas de algodão e soja.', 3, SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO TB_ALERTA_AGRICOLA (ID_FAZENDA, TP_ALERTA, DS_ALERTA, TP_NIVEL_RISCO, DT_GERACAO)
VALUES (2, 1, 'Condições de seca detectadas: precipitação 0.0mm, umidade 30.0%. Irrigação urgente necessária.', 3, SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO TB_ALERTA_AGRICOLA (ID_FAZENDA, TP_ALERTA, DS_ALERTA, TP_NIVEL_RISCO, DT_GERACAO)
VALUES (2, 3, 'NDVI baixo detectado: 0.0750. Vegetação com baixo vigor ou solo exposto. Verifique disponibilidade de nutrientes e hídrica.', 4, SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO TB_ALERTA_AGRICOLA (ID_FAZENDA, TP_ALERTA, DS_ALERTA, TP_NIVEL_RISCO, DT_GERACAO)
VALUES (4, 4, 'Precipitação excessiva: 55.3mm. Risco de encharcamento do solo e doenças fúngicas. Verifique o sistema de drenagem.', 3, SYSTIMESTAMP - INTERVAL '2' DAY);

INSERT INTO TB_ALERTA_AGRICOLA (ID_FAZENDA, TP_ALERTA, DS_ALERTA, TP_NIVEL_RISCO, DT_GERACAO)
VALUES (5, 5, 'Velocidade do vento elevada: 45.5 km/h. Risco de danos mecânicos às plantas. Suspenda pulverizações.', 2, SYSTIMESTAMP - INTERVAL '1' DAY);

-- ============================================================
-- 11. INSERTS — HISTÓRICO DE CONSULTAS
-- ============================================================
INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (1, 'GET /api/monitoramento/clima/{fazendaId}', SYSTIMESTAMP - INTERVAL '5' DAY, 432, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (1, 'GET /api/monitoramento/vegetacao/{fazendaId}', SYSTIMESTAMP - INTERVAL '5' DAY, 518, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (1, 'GET /api/monitoramento/clima/{fazendaId}', SYSTIMESTAMP - INTERVAL '3' DAY, 389, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (2, 'GET /api/monitoramento/clima/{fazendaId}', SYSTIMESTAMP - INTERVAL '2' DAY, 612, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (2, 'GET /api/monitoramento/vegetacao/{fazendaId}', SYSTIMESTAMP - INTERVAL '2' DAY, 1023, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (2, 'GET /api/monitoramento/clima/{fazendaId}', SYSTIMESTAMP - INTERVAL '1' DAY, 455, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (3, 'GET /api/monitoramento/vegetacao/{fazendaId}', SYSTIMESTAMP - INTERVAL '3' DAY, 708, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (4, 'GET /api/monitoramento/clima/{fazendaId}', SYSTIMESTAMP - INTERVAL '2' DAY, 521, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (5, 'GET /api/monitoramento/clima/{fazendaId}', SYSTIMESTAMP - INTERVAL '1' DAY, 390, 1);

INSERT INTO TB_HISTORICO_CONSULTA (ID_FAZENDA, DS_ENDPOINT, DT_CONSULTA, NR_TEMPO_RESP_MS, FL_SUCESSO)
VALUES (5, 'GET /api/monitoramento/vegetacao/{fazendaId}', SYSTIMESTAMP - INTERVAL '1' DAY, 15000, 0);

COMMIT;

-- ============================================================
-- 12. VERIFICAÇÃO FINAL
-- ============================================================
SELECT 'TB_FAZENDA'            AS tabela, COUNT(*) AS registros FROM TB_FAZENDA           UNION ALL
SELECT 'TB_CULTURA_AGRICOLA'   AS tabela, COUNT(*) AS registros FROM TB_CULTURA_AGRICOLA  UNION ALL
SELECT 'TB_MON_CLIMATICO'      AS tabela, COUNT(*) AS registros FROM TB_MON_CLIMATICO     UNION ALL
SELECT 'TB_MON_VEGETACAO'      AS tabela, COUNT(*) AS registros FROM TB_MON_VEGETACAO     UNION ALL
SELECT 'TB_ALERTA_AGRICOLA'    AS tabela, COUNT(*) AS registros FROM TB_ALERTA_AGRICOLA   UNION ALL
SELECT 'TB_HISTORICO_CONSULTA' AS tabela, COUNT(*) AS registros FROM TB_HISTORICO_CONSULTA;
