// <auto-generated />
using System;
using AgroSatMonitor.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AgroSatMonitor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530155305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("MonitoramentoBaseSequence");

            modelBuilder.Entity("AgroSatMonitor.API.Entities.AlertaAgricola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_GERACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_ALERTA");

                    b.Property<int>("FazendaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FAZENDA");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_NIVEL_RISCO");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_ALERTA");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.ToTable("TB_ALERTA_AGRICOLA", (string)null);
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.CulturaAgricola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CULTURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FazendaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FAZENDA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CULTURA");

                    b.Property<string>("Safra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_SAFRA");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TP_CULTURA");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.ToTable("TB_CULTURA_AGRICOLA", (string)null);
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.Fazenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FAZENDA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaHectares")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_AREA_HECTARES");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("SG_ESTADO");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_FAZENDA");

                    b.HasKey("Id");

                    b.ToTable("TB_FAZENDA", (string)null);
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.HistoricoConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_HISTORICO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CONSULTA");

                    b.Property<string>("EndpointConsultado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DS_ENDPOINT");

                    b.Property<int>("FazendaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FAZENDA");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("FL_SUCESSO");

                    b.Property<long>("TempoRespostaMs")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_TEMPO_RESP_MS");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.ToTable("TB_HISTORICO_CONSULTA", (string)null);
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.MonitoramentoBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MON_VEG")
                        .HasDefaultValueSql("\"MonitoramentoBaseSequence\".NEXTVAL");

                    OraclePropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<int>("FazendaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FAZENDA");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_LONGITUDE");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.MonitoramentoClimatico", b =>
                {
                    b.HasBaseType("AgroSatMonitor.API.Entities.MonitoramentoBase");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<double>("Precipitacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_PRECIPITACAO");

                    b.Property<double>("Temperatura")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_TEMPERATURA");

                    b.Property<double>("Umidade")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_UMIDADE");

                    b.Property<double>("VelocidadeVento")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_VEL_VENTO");

                    b.HasIndex("FazendaId");

                    b.ToTable("TB_MON_CLIMATICO", (string)null);
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.MonitoramentoVegetacao", b =>
                {
                    b.HasBaseType("AgroSatMonitor.API.Entities.MonitoramentoBase");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<double>("Ndvi")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_NDVI");

                    b.Property<int>("NivelSaudeVegetacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_NIVEL_SAUDE");

                    b.HasIndex("FazendaId");

                    b.ToTable("TB_MON_VEGETACAO", (string)null);
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.AlertaAgricola", b =>
                {
                    b.HasOne("AgroSatMonitor.API.Entities.Fazenda", "Fazenda")
                        .WithMany("Alertas")
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.CulturaAgricola", b =>
                {
                    b.HasOne("AgroSatMonitor.API.Entities.Fazenda", "Fazenda")
                        .WithMany("Culturas")
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.HistoricoConsulta", b =>
                {
                    b.HasOne("AgroSatMonitor.API.Entities.Fazenda", "Fazenda")
                        .WithMany("HistoricosConsulta")
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.MonitoramentoClimatico", b =>
                {
                    b.HasOne("AgroSatMonitor.API.Entities.Fazenda", "Fazenda")
                        .WithMany("MonitoramentosClimaticos")
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.MonitoramentoVegetacao", b =>
                {
                    b.HasOne("AgroSatMonitor.API.Entities.Fazenda", "Fazenda")
                        .WithMany("MonitoramentosVegetacao")
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("AgroSatMonitor.API.Entities.Fazenda", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Culturas");

                    b.Navigation("HistoricosConsulta");

                    b.Navigation("MonitoramentosClimaticos");

                    b.Navigation("MonitoramentosVegetacao");
                });
#pragma warning restore 612, 618
        }
    }
}
